### ISSUE TITLE
Roadmap 0

### ISSUE THREAD

**Issue by hazelwolf** [hazelWolf/DroneUnity3D#1]
Started as backyard project to experiment in Unity with Drone technology and mixing it with other AR, VR, AI and IoT tech. 

**Master branch is highly unstable use at your own discretion**

Following things would be added under first release tag 
To Do's

- [x] UDP connection with drone
- [x] Add functionality to check battery and send takeoff and land commands
- [ ] Add multi-threading and receive info on multi thread from Drone
- [ ] Test on Android,Windows x64 and UWP (Holo Lens 1st Gen)
- [ ] Add movement 
- [ ] Create custom controller for Drone in AR and VR
